# Generated by Django 5.0 on 2026-04-18 11:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=core.models.generate_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
